# Generated by Django 4.2.7 on 2026-07-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('industry', models.CharField(max_length=64)),
                ('overall_score', models.FloatField()),
                ('rule_based_score', models.FloatField()),
                ('ml_predicted_score', models.FloatField()),
                ('feature_scores', models.JSONField()),
                ('risk_blockers', models.JSONField(default=list)),
                ('highway_info', models.JSONField(default=dict)),
                ('raw_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='analysis_an_latitud_61fc36_idx')],
            },
        ),
    ]
