# Generated by Django 4.2.7 on 2026-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='criteria_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='district',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='highway_corridor_bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='lightgbm_predicted_label',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='lightgbm_probabilities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='mcda_base_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='mcda_final_suitability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='nearest_highway_ref',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='nearest_river_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='river_reliability_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
