# Generated by Django 4.2.7 on 2026-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisrun_criteria_breakdown_analysisrun_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='better_site_suggestion',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
