# Generated by Django 4.2.7 on 2026-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_road_railway_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railway',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'managed': False},
        ),
    ]
