# Generated by Django 4.2.7 on 2026-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
